### ISSUE TITLE
Find good structure for options type

### ISSUE THREAD

**Issue by ailox** [gdm85/go-libdeluge#13]
In commit e1f610e395279d1ccc6db720efb1b06d875579b6 the Options object was changed from a hashmap to a strongly typed struct. This is a change I liked, but i quickly noticed that it makes the API a little more difficult to use.
When passing options, now all values need to be defined, as their ~null~ *empty* values will overwrite deluge's defaults.

Ignoring the empty values is also not a solution, or the user will become unable to set values such as '0' (int) or 'false' (bool).

Adding pointers to all the attributes will make the initialization harder.

`sql.NullString`, `sql.NullInt`… could be used, but on second thought it seems a little strange to import the sql package to initialize the deluge client.

Reverting back to the hashmap will require a lot of magic strings, but will make the version handling easier to implement (since it is then left to the user to provide valid option name keys).

Original comment was here https://github.com/gdm85/go-libdeluge/commit/e1f610e395279d1ccc6db720efb1b06d875579b6#r36456065

**Comment by ailox** [comment]
Another way would be to have a `NewOptions()` or `DefaultOptions()` constructor, that has useful default values. Or maybe even fetches them from the Server (I haven't checked if that is possible)

**Comment by ailox** [comment]
_Originally posted by @gdm85 in https://github.com/gdm85/go-libdeluge/pull/12#issuecomment-566423509_

> @ailox yes, I mentioned this in above comment. At this point I wonder:
> * what will the Go default values do on deluge daemon side? Can we set the proper deluge default values (`-1` etc) on Go side? (ugly, because deluge daemon might change them, but would work)
>
> I am not in favour of a map of `interface{}` values as it was done before so it's either that or the `nil` pointer approach.
>
> A third way would be to compare with `reflect.Zero()` and skip those, but it would disallow the user to set those values explicitly, so also not a nice solution.
>
> Interestingly, the deprecated APIs would not pose such initialisation problems.

**Comment by ailox** [comment]
As a workaround we can also implement something like a bit field, that will be "true" if the value has changed? Something like
```go
type changedMap map[interface{}]bool

type Options struct {
    // …
    changedMap  changedMap
}

func (o *Options) isChanged(interface{}) bool {}
func (o *Options) setChanged(interface{}) {}

// and a lot of Setter methods that do something like:
func (o *Options) SetMaxDownloadSpeed(kbits int) {
    o.MaxDownloadSpeed = kbits
    o.changedMap[&o.MaxDownloadSpeed] = true
}

// and we can check later with the options object if the attribute has been set manually:
if o.isChanged(&o.AllocateStorage) {
    // …
}
```

**Comment by gdm85** [comment]
@ailox deluge daemon itself does something like that, they call the setter only when the value is specified.

I will settle for the pointer approach; I do not consider valid possibilities adapting to the loose style of deluge daemon nor following other Go projects on this.

Using the `map[string]interface{}` is not different than allowing a JSON string payload, and it does not prevent the user from passing the wrong option types.
