### ISSUE TITLE
Add 'Darwin' Support

### ISSUE THREAD

**Issue by sloan-848** [gdm85/go-libdeluge#2]
When this library is built on Darwin/OS X/macos, the following error occurs:
```bash
$ go build .
# github.com/gdm85/go-libdeluge
./keep_alive.go:50:89: undefined: syscall.TCP_KEEPIDLE
./keep_alive.go:54:89: undefined: syscall.TCP_KEEPCNT
./keep_alive.go:58:89: undefined: syscall.TCP_KEEPINTVL
```

I believe this is because these constants in the `syscall` package are OS-dependent, and are not exposed on the Darwin platform.

**Comment by sloan-848** [comment]
It appears that the `keep_alive.go` file is based on the [felixge/tcpkeepalive](https://github.com/felixge/tcpkeepalive) project. That project has platform-specific implementations of this code; perhaps we could just use those implementations and make platform-specific versions of `keep_alive.go`?

**Comment by gdm85** [comment]
@sloan-848 I did not add other platforms because from preliminary tests it seemed like TCP keep-alive was not working; I was indeed planning to remove it completely if it could not be made to work on Linux.

I see you have opened PR #3 so for now that can be merged and this issue fixed.
