### ISSUE TITLE
Feature: Windows support

### ISSUE THREAD

**Issue by l3uddz** [gdm85/go-libdeluge#23]
Hi,

Is Windows support planned?

Currently, builds fail for Windows with:

```    
⨯ release failed after 99.97s error=failed to build for windows_amd64: # github.com/gdm85/go-libdeluge


/go/pkg/mod/github.com/gdm85/go-libdeluge@v0.3.2/keep_alive.go:42:11: undefined: setIdle
/go/pkg/mod/github.com/gdm85/go-libdeluge@v0.3.2/keep_alive.go:46:11: undefined: setCount
/go/pkg/mod/github.com/gdm85/go-libdeluge@v0.3.2/keep_alive.go:50:11: undefined: setInterval
make: *** [Makefile:85: snapshot] Error 1
ERROR: Job failed: exit code 2```

**Comment by gdm85** [comment]
Looks like keep-alive support was added in https://github.com/golang/go/commit/5bd7e9c54f946eec95d32762e7e9e1222504bfc1 and it is enabled by default; I will disable this code.

**Comment by gdm85** [comment]
Current `master` builds on Windows, but it does not mean it's working or supported. You can test it now.
