### ISSUE TITLE
Error parsing Deluge Output:  "ETA" field

### ISSUE THREAD

**Issue by davidnewhall** [gdm85/go-libdeluge#4]
```
Error: field "ETA": value 3.935657e+08: cannot convert from float32 into *int64
```

I tried changing the type for `ETA` to various different things, like float64, float32, int. Nothing seems to work out. I'd like to use this as a library, but I'm not sure how to pull the torrent list. Any ideas or help is appreciated.

This is the output when trying other types:
```
Error: field "ETA": value 1.9893198e+08: cannot convert from float32 into *int
Error: field "ETA": value 848147.25: cannot convert from float32 into *int64
Error: field "ETA": value 0: cannot convert from int8 into *float32
Error: field "ETA": value 0: cannot convert from int8 into *float64
Error: field "ETA": value 1.1388818e+06: cannot convert from float32 into *int8
```

Thanks for looking!

**Comment by gdm85** [comment]
Which version of deluge are you using? I have never seen these errors.

Can you run `bin/delugecli ... -l DEBUG -list` and attach the generated `testlist.rnc`?

Be aware that it will contain the raw data, so there might be privacy concerns to consider.
You could run `base64 < testlist.rnc` and save the result in a temporary pastebin, otherwise attaching it here would also work.

**Comment by davidnewhall** [comment]
Latest version of Deluge, 1.3.15, running on macOS with over 500 seeding torrents. I wrote a deluge lib at also, but it uses the webUI api to pull the torrent lust. I've found the webUI to be wildly unstable and basically useless. I'm trying to adapt your lib into my code to use RPC calls directly the daemon. I do not understand what the `rencode` lib is doing, and my ability to troubleshoot it is waning. 
When I had this problem, I wound up using `json.Number` as the type and never bothered to do anything with it (because my app doesn't need the eta). Example: https://github.com/davidnewhall/unpacker-poller/blob/master/deluge/config.go#L115

That command you provided doesn't really output much; doesn't seem like useful data in the `ist` file that was created.I'm also not really willing to post a list of my torrents on the Internet, but I'm wiling to show you the `ETA` output for them.

**Comment by davidnewhall** [comment]
If I use the built-in CLI, I get this:
```
DELUGE_PASSWORD="8b9b5189f063da073abd4243c0aad57c4eede8b6" ./cli -list
Deluge daemon version: 1.3.15
available methods: [core.upload_plugin core.rescan_plugins core.force_recheck label.set_config core.glob core.remove_torrent core.resume_all_torrents core.queue_top label.add label.set_torrent daemon.get_method_list label.remove core.set_torrent_options core.set_torrent_prioritize_first_last core.get_session_state core.set_torrent_move_completed core.get_available_plugins core.set_torrent_file_priorities notifications.get_handled_events webui.got_deluge_web core.get_config core.disable_plugin core.test_listen_port core.connect_peer notifications.set_config core.enable_plugin core.get_filter_tree core.set_torrent_remove_at_ratio core.get_torrent_status core.get_config_values label.get_config core.pause_torrent core.move_storage core.force_reannounce core.add_torrent_file core.get_listen_port core.set_torrent_move_completed_path core.set_torrent_stop_at_ratio core.rename_folder core.add_torrent_url core.get_enabled_plugins core.get_libtorrent_version label.set_options core.get_path_size core.set_torrent_max_connections label.get_labels core.get_config_value core.get_session_status core.create_torrent notifications.get_config core.add_torrent_magnet webui.stop daemon.info label.get_options core.set_torrent_stop_ratio core.set_torrent_auto_managed core.pause_all_torrents webui.get_config core.get_torrents_status core.rename_files core.get_free_space core.queue_bottom core.set_torrent_max_upload_speed webui.start core.resume_torrent core.set_torrent_max_upload_slots core.set_config core.get_cache_status core.queue_down daemon.shutdown core.get_num_connections core.set_torrent_max_download_speed core.queue_up core.set_torrent_trackers webui.set_config]
ERROR: could not list all torrents: strconv.Atoi: parsing "20E02.720p.HDTV.x264-ALTEREGO/the.bachelor.s20e02.720p.hdtv.x264-alterego.r05j\x85index\a\x84size@\x02\xfa\xf0\x80\x86offset@\x11\xe1\xadf\x84path91": invalid syntax
home:~ cartcrafter$
```

**Comment by gdm85** [comment]
The `.rnc` file is generated only if debug log level is enabled; it contains the raw data needed to troubleshoot decoding problems like these (the ETA error and the length decoding issue in the previous comment) . Without the raw data I cannot see what is the specific decoding issue.

**Comment by davidnewhall** [comment]
Can you shoot me an email or tell me a way to send this file to you? david at sleepers dot pro
Thanks!

**Comment by gdm85** [comment]
The easiest is to make it base64-encoded and then paste it here: https://keybase.io/gdm85

**Comment by davidnewhall** [comment]
gzip is < half a meg, base64 > 6 meg, so I emailed it to ya. Thanks!

**Comment by gdm85** [comment]
If you apply base64 after gzip, it's still around ~0.5MB (base64 adds always 33% of the size) :wink: 

The bug has been fixed; a conversion from `int8` to `float32` was not covered in [go-rencode](https://github.com/gdm85/go-rencode). This all stems from the fact that there is no specification for the Deluge remote API...so I could not/cannot find anywhere what the response is supposed to contain (and I suspect it might be always variadic due to how python works).
