### ISSUE TITLE
Local daemon connections failing to establish

### ISSUE THREAD

**Issue by Schachte** [gdm85/go-libdeluge#41]
Hey great library!

I'm trying to connect to the daemon locally:

```go
	deluge := delugeclient.NewV2(delugeclient.Settings{
		Hostname:             "127.0.0.1",
		Port:                 58846,
		Login:                "localclient",
		Password:             "deluge",
		DebugServerResponses: true,
	})

	// perform connection to Deluge server
	err := deluge.Connect()
	if err != nil {
		log.Fatal(err)
	}
```

The port is open and exposed, can confirm via `lsof -i :58846`. 

Connection fails with no context printing `EOF`. I'm not sure why. I'm debugging into the connection into the code and it fails around L336 of `delugeclient` on this line:

```
_, err = c.safeConn.Write(header[:])
```

What am I missing?

**Comment by Schachte** [comment]
I've
- enabled remote connections
- tried pulling the encrypted password

Can confirm I can connect to the console via the `deluge-console` on the container

```
deluge-console "connect localhost:58846 deluge d0e89ab7d2a74833f555cccdaf7dcd53bcf85ddc; info"
```

No issues when manually doing this.

**Comment by gdm85** [comment]
Most likely this is an issue of V1/V2 incompatibility; what version is your deluged daemon? Will close it for now as I assume you have already figured it out by now.
